; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35217.0 

	TITLE	c:\COAL\_COAL2025_32\MyAsm\asmones_mainasm\asmones_1\Debug\ones_c.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__8AADE9C9_ones_c@cpp DB 01H
msvcjmc	ENDS
PUBLIC	_ones_c@8
PUBLIC	__JustMyCode_Default
EXTRN	@__CheckForDebuggerJustMyCode@4:PROC
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /ZI
; File c:\COAL\_COAL2025_32\MyAsm\asmones_mainasm\ones_c.cpp
;	COMDAT _ones_c@8
_TEXT	SEGMENT
_i$1 = -8						; size = 4
_res$ = -4						; size = 4
_data$ = 8						; size = 4
_n$ = 12						; size = 4
_ones_c@8 PROC						; COMDAT

; 1    : extern "C" int _stdcall ones_c(unsigned data, int n) {

	push	ebp
	mov	ebp, esp
	sub	esp, 72					; 00000048H
	push	ebx
	push	esi
	push	edi
	mov	ecx, OFFSET __8AADE9C9_ones_c@cpp
	call	@__CheckForDebuggerJustMyCode@4
	npad	1

; 2    : 	int res = 0;

	mov	DWORD PTR _res$[ebp], 0

; 3    : 	for (int i = 0; i < n; ++i) {

	mov	DWORD PTR _i$1[ebp], 0
	jmp	SHORT $LN4@ones_c
$LN2@ones_c:
	mov	eax, DWORD PTR _i$1[ebp]
	add	eax, 1
	mov	DWORD PTR _i$1[ebp], eax
$LN4@ones_c:
	mov	eax, DWORD PTR _i$1[ebp]
	cmp	eax, DWORD PTR _n$[ebp]
	jge	SHORT $LN3@ones_c

; 4    : 		if (data & 1) ++res;

	mov	eax, DWORD PTR _data$[ebp]
	and	eax, 1
	je	SHORT $LN5@ones_c
	mov	eax, DWORD PTR _res$[ebp]
	add	eax, 1
	mov	DWORD PTR _res$[ebp], eax
$LN5@ones_c:

; 5    : 		data = data >> 1;

	mov	eax, DWORD PTR _data$[ebp]
	shr	eax, 1
	mov	DWORD PTR _data$[ebp], eax

; 6    : 	}

	jmp	SHORT $LN2@ones_c
$LN3@ones_c:

; 7    : 	return res;

	mov	eax, DWORD PTR _res$[ebp]

; 8    : }

	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	8
_ones_c@8 ENDP
_TEXT	ENDS
END
