; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35217.0 

	TITLE	c:\coal\_coal2025_32\myasm\asmones_maincpp\onesasm2\release\ones_c.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

EXTRN	@__security_check_cookie@4:PROC
PUBLIC	?ones_c@@YAHIH@Z				; ones_c
EXTRN	___CxxFrameHandler3:PROC
EXTRN	___security_cookie:DWORD
; Function compile flags: /Ogtp
;	COMDAT ?ones_c@@YAHIH@Z
_TEXT	SEGMENT
?ones_c@@YAHIH@Z PROC					; ones_c, COMDAT
; _data$dead$ = ecx
; _n$dead$ = edx
; File c:\COAL\_COAL2025_32\MyAsm\asmones_maincpp\ones_c.cpp
; Line 1
	push	ebp
	mov	ebp, esp
	push	ecx
	push	ebx
	push	esi
; Line 2
	xor	esi, esi
	mov	ecx, -2					; fffffffeH
	push	edi
; Line 3
	xor	edi, edi
	lea	ebx, DWORD PTR [esi+16]
$LL4@ones_c:
; Line 4
	mov	eax, ecx
; Line 5
	shr	ecx, 1
	mov	edx, ecx
	and	eax, 1
	and	edx, 1
	shr	ecx, 1
	add	esi, eax
	add	edi, edx
	sub	ebx, 1
	jne	SHORT $LL4@ones_c
; Line 7
	lea	eax, DWORD PTR [edi+esi]
	pop	edi
	pop	esi
	pop	ebx
; Line 8
	mov	esp, ebp
	pop	ebp
	ret	0
?ones_c@@YAHIH@Z ENDP					; ones_c
_TEXT	ENDS
END
