; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35217.0 

	TITLE	c:\coal\_coal2025_32\myasm\asmones_mainasm\asmones_1\release\ones_c.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

EXTRN	@__security_check_cookie@4:PROC
PUBLIC	_ones_c@8
END
